Added support for TLS; deleted trailing spaces
enhanced error message reporting
added auth checking to reenroll test

Change-Id: I5225097a0a9257b6f618fe248e43fde6fe415a96
Signed-off-by: rennman <eabailey@us.ibm.com>

diff --git a/scripts/fabric-ca_utils b/scripts/fabric-ca_utils
--- a/scripts/fabric-ca_utils
+++ b/scripts/fabric-ca_utils
@@ -2,11 +2,19 @@
 DATE='date +%Y-%m-%d'
 TIME='date +%I:%M:%S%p'
 
-function genClientConfig() {
+genClientConfig() {
    local CLIENTCONFIG="$1"
+   test -z "${FABRIC_CA}" && FABRIC_CA="$GOPATH/src/github.com/hyperledger/fabric-ca"
+   test -z "${TESTDATA}" && TESTDATA="$FABRIC_CA/testdata"
+
    cat > "$CLIENTCONFIG" <<-EOF
 {
-  "tls_disable":true
+  "tls_disable":false,
+  "ca_certfiles":["$TESTDATA/root.pem"],
+  "client":{
+             "keyfile":"$TESTDATA/tls_client-key.pem",
+             "certfile":"$TESTDATA/tls_client-cert.pem"
+  }
 }
 EOF
 }
@@ -50,7 +58,7 @@ pollServer() {
    while test "$(($(date +%s)-starttime))" -lt "$timeout" -a $rc -ne 0
    do
       sleep 1
-      printf "\r%s%03d" "Waiting for $app start on $host:$port ..." "$now"
+      printf "\r%s%03d" "Waiting for $app start on $host:$port ..." "$(($(date +%s)-starttime))"
       isReachable "$host" "$port"
       rc=$?
    done
@@ -68,9 +76,9 @@ CleanUp() {
    ###############################################################################
    # Summary
    ###############################################################################
-   echo "" 
-   echo "#########################################################################" 
-   printf "RC: $RC, $TESTCASE " 
+   echo ""
+   echo "#########################################################################"
+   printf "RC: $RC, $TESTCASE "
 
    if test "$RC" -eq 0; then
       RESULT="PASSED"
@@ -84,10 +92,18 @@ CleanUp() {
    printf "$(TimeStamp) $TESTCASE ENDED\n"
    echo "#########################################################################"
 
-   TimeStamp 
+   TimeStamp
    printf "%s test ended.\n" $TESTCASE
 }
 
+
+function ErrorMsg() {
+   local msg="$1"
+   local rc="$2"
+   : ${rc:="RC"}
+   echo -e "\033[31m ****** ERROR ****** $msg \033[0m"
+   let $rc+=1
+}
 
 function ErrorExit() {
    $FABRIC_CA/scripts/fabric-ca_setup.sh -R
@@ -96,7 +112,7 @@ function ErrorExit() {
 }
 
 function verifyServerTraffic() {
-   # verifyServerTraffic 
+   # verifyServerTraffic
    # validate that backend <server_name>
    # got at least <num_requests> requests from client
    # with a minimum of <percent> HTTP status code <code>
@@ -108,7 +124,7 @@ function verifyServerTraffic() {
    local op="$6"
    local rc=0
 
-    # default 
+    # default
     #  server got at least one request
     #  all received requests were successfully served
     : ${haproxy_addr:="localhost:10888"}
@@ -124,8 +140,8 @@ function verifyServerTraffic() {
            /Cum. sessions:/ {sessions=$NF}
            $0~c {gsub(/[(%)]/,"",$NF);status=$NF}
            END {print sessions" "status}')
-   eval test "${result%% *}" -$op "$num_requests" 2>/dev/null; rc=$((rc+$?)) 
-   eval test "${result##* }" -$op "$percent" 2>/dev/null; rc=$((rc+$?)) 
+   eval test "${result%% *}" -$op "$num_requests" 2>/dev/null; rc=$((rc+$?))
+   eval test "${result##* }" -$op "$percent" 2>/dev/null; rc=$((rc+$?))
 
    return $rc
 }
@@ -133,10 +149,10 @@ function verifyServerTraffic() {
 function printAuth() {
    CLIENTCERT=$1
    CLENTKEY=$2
-   
+
    : ${CLIENTCERT:="$HOME/fabric-ca/cert.pem"}
    : ${CLIENTKEY:="$HOME/fabric-ca/key.pem"}
-   
+
    echo CERT:
    openssl x509 -in $CLIENTCERT -text 2>&1 | sed 's/^/    /'
    type=$(cat $CLIENTKEY | head -n1 | awk '{print tolower($2)}')
@@ -151,7 +167,7 @@ function startHttp() {
    cd $rootdir
    python -m SimpleHTTPServer $port &
    HTTP_PID=$!
-   pollServer python localhost "$HTTP_PORT" && return $HTTP_PID || return -1 
+   pollServer python localhost "$HTTP_PORT" && return $HTTP_PID || return -1
 }
 
 function keyCheck() {
@@ -160,10 +176,21 @@ function keyCheck() {
    local alg="$3"
    : ${alg:="rsa"}
    test -f "$cert" -a -f "$key" || return 1
+
    # check to see that the public/private key pair match
-   k_hash=$(openssl $alg -noout -modulus -in $key  2>&1| awk -F'=' '/=/ {print $2}' | openssl md5 | awk '{print $NF}')
-   c_hash=$(openssl x509 -noout -modulus -in $cert 2>&1| awk -F'=' '/=/ {print $2}' | openssl md5 | awk '{print $NF}')
+   case "$alg" in
+   rsa|dsa)
+       k_hash=$(openssl $alg -noout -modulus -in $key  2>&1| awk -F'=' '/=/ {print $2}' | openssl md5 | awk '{print $NF}')
+       c_hash=$(openssl x509 -noout -modulus -in $cert 2>&1| awk -F'=' '/=/ {print $2}' | openssl md5 | awk '{print $NF}')
+   ;;
+   *)
+       k_hash=$(openssl $alg        -pubout -in $key  2>/dev/null| openssl md5 | awk '{print $NF}')
+       c_hash=$(openssl x509 -noout -pubkey -in $cert            | openssl md5 | awk '{print $NF}')
+   ;;
+   esac
+
    test -z "$k_hash" -o -z "$c_hash" && return 1
    test "$k_hash" == "$c_hash" || return 1
+
    return 0
 }
