Add TLS support to fabric-ca-server's LDAP client
TLS configuration support added for LDAP client of
the fabric-ca server.

https://jira.hyperledger.org/browse/FAB-1463

Change-Id: Ib0644805ad4cde0be527f82250b22c9d3b46ef7d
Signed-off-by: Saad Karim <skarim@us.ibm.com>

diff --git a/scripts/run_ldap_tests b/scripts/run_ldap_tests
--- a/scripts/run_ldap_tests
+++ b/scripts/run_ldap_tests
@@ -8,10 +8,12 @@
 # IMAGE is the name of docker image
 OLC=openldap-fabric-ca
 IMAGE=hyperledger/openldap
+OLC_tls=openldap-fabric-ca-tls
 CA=$GOPATH/src/github.com/hyperledger/fabric-ca
 
 # Start the LDAP container
 function startContainer {
+  echo "Start LDAP server without TLS enabled"
    CID=`docker ps -q -f name=$OLC`
    if [ "$CID" != "" ]; then
       echo "$OLC is already running at $CID"
@@ -23,7 +25,7 @@ function startContainer {
       docker start $CID
    else
       echo "Downloading and starting $OLC ..."
-      docker run -p 10389:389 -p 10636:636 --name $OLC --detach $IMAGE > /dev/null
+      docker run -p 10389:389 --name $OLC --detach $IMAGE > /dev/null
    fi
    CID=`docker ps -q -f name=$OLC`
    if [ "$CID" != "" ]; then
@@ -31,6 +33,33 @@ function startContainer {
       return 0
    fi
    echo "$OLC failed to start"
+   return 1
+}
+
+# Start the LDAP container with TLS
+function startTLSContainer {
+   echo "Start LDAP server with TLS enabled"
+   CID=`docker ps -q -f name=$OLC_tls`
+   if [ "$CID" != "" ]; then
+      echo "$OLC_tls is already running at $CID"
+      return 0
+   fi
+   CID=`docker ps -a -q -f name=$OLC_tls`
+   if [ "$CID" != "" ]; then
+      echo "Starting $OLC_tls ..."
+      docker start $CID
+   else
+      echo "Downloading and starting $OLC_tls ..."
+      docker run -p 10636:636 --volume $GOPATH/src/github.com/hyperledger/fabric-ca/testdata:/container/service/slapd/assets/certs \
+      --env LDAP_TLS_CRT_FILENAME=tls_server-cert.pem --env LDAP_TLS_KEY_FILENAME=tls_server-key.pem --env LDAP_TLS_CA_CRT_FILENAME=root.pem \
+      --name $OLC_tls --detach $IMAGE > /dev/null
+   fi
+   CID=`docker ps -q -f name=$OLC_tls`
+   if [ "$CID" != "" ]; then
+      echo "$OLC_tls has been started"
+      return 0
+   fi
+   echo "$OLC_tls failed to start"
    return 1
 }
 
@@ -42,15 +71,18 @@ function addUser {
    USER=uid=jsmith,dc=example,dc=org
    USERPW=jsmithpw
    docker cp $CA/scripts/$LDIF $OLC:/tmp
+   docker cp $CA/scripts/$LDIF $OLC_tls:/tmp
    docker exec $OLC ldapadd -cxD $ADMIN -w $ADMINPW -f /tmp/$LDIF
    docker exec $OLC ldappasswd -xD $ADMIN -w $ADMINPW $USER -s $USERPW
+   docker exec $OLC_tls ldapadd -cxD $ADMIN -w $ADMINPW -f /tmp/$LDIF
+   docker exec $OLC_tls ldappasswd -xD $ADMIN -w $ADMINPW $USER -s $USERPW
    return 0
 }
 
 # Run the LDAP test cases
 function runTests {
    echo "Running LDAP test cases ..."
-   cd $CA/cli/server/ldap
+   cd $CA/lib/ldap
    go test . -cover | tee /tmp/ldap-test.results
    echo "LDAP test cases are complete"
 }
@@ -71,6 +103,11 @@ function removeImage {
 }
 
 startContainer
+if [ $? -ne 0 ]; then
+   exit 1
+fi
+
+startTLSContainer
 if [ $? -ne 0 ]; then
    exit 1
 fi
